### ISSUE TITLE
Can’t install on mac

### ISSUE THREAD

**Issue by niso120b** [rich-newman/typescript-html-application-vs2017-template#2]
Can’t install this plugin on visual studio on MacBook, you have any solution?!

**Comment by rich-newman** [comment]
This template is for the version of Visual Studio 2017 that runs on Windows.  The version of Visual Studio that runs on the Mac is a different application and has a different way of constructing templates.  So this template will not work on the Mac.  There's also Visual Studio Code, available on both Windows and the Mac and Linux, which is different from the other two, and again has a different way of constructing templates.  Personally I'd have preferred it if Microsoft had given these things different names: it's confusing for everybody.
