### ISSUE TITLE
Add VS 2022  Support

### ISSUE THREAD

**Issue by talley** [rich-newman/typescript-html-application-vs2017-template#4]
Add VS 2022  Support

**Comment by rich-newman** [comment]
The template has now been upgraded and is available for Visual Studio 2022.  As usual, you can [download it from Marketplace](https://marketplace.visualstudio.com/items?itemName=Rich-Newman.TypeScriptHTMLApplicationTemplate), or search for 'TypeScript HTML Application' in the Manage Extensions window inside Visual Studio.

**Comment by rich-newman** [comment]
Apologies, the version that was released had issues in VS2022, and has been rolled back.  Reopening the issue.

**Comment by rich-newman** [comment]
There is now [a version of the template that works in Visual Studio 2022 available on Marketplace](https://marketplace.visualstudio.com/items?itemName=Rich-Newman.TypeScriptHTMLApplicationTemplate2022) and in the Manage Extensions window.

The issue with the first version released above was that TypeScript is no longer natively available in Visual Studio.  The template now installs TypeScript via a NuGet package when you create a solution.
